# Generated by Django 6.0.5 on 2026-05-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_actionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#1a237e", max_length=20, verbose_name="Couleur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AddField(
            model_name="journal",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journaux",
                to="app.categorie",
                verbose_name="Catégorie",
            ),
        ),
    ]
